### ISSUE TITLE
FYI: I added this into Zed's extensions

### ISSUE THREAD

**Issue by AlbertMarashi** [Ce11an/tree-sitter-surrealql#19]
Thank you for building and maintaining this.

I created a https://zed.dev extension for this
- https://github.com/siteforge-io/surql-zed

I have some critiques about how you may be parsing some things inside the grammar, so I may come back with some contributions if I have time - but it's nice to see that this exists.

**Comment by Ce11an** [comment]
> Thank you for building and maintaining this.
> 
> 
> 
> I created a https://zed.dev extension for this
> 
> - https://github.com/siteforge-io/surql-zed
> 
> 
> 
> I have some critiques about how you may be parsing some things inside the grammar, so I may come back with some contributions if I have time - but it's nice to see that this exists.
> 
> 

Thanks, I'll test out it and add it as a link 😊
